import { useState } from 'react';
import { Link } from 'react-router-dom';
import './LegalPages.css';

const EFFECTIVE_DATE = '9 September 2026';

export function CookieConsentBanner() {
  const [visible, setVisible] = useState(
    () => localStorage.getItem('shambani_cookie_choice') === null
  );

  const choose = (choice: 'essential' | 'all') => {
    localStorage.setItem('shambani_cookie_choice', choice);
    setVisible(false);
  };

  if (!visible) return null;

  return (
    <aside className="cookie-banner" aria-label="Cookie notice">
      <div className="cookie-content">
        <div className="cookie-text">
          <span className="cookie-icon" aria-hidden="true">🍪</span>
          <div>
            <h3>Cookie choice</h3>
            <p>
              This prototype uses essential browser storage for interface preferences. Optional analytics must not run unless you agree. Read the{' '}
              <Link to="/privacy">privacy notice</Link>.
            </p>
          </div>
        </div>
        <div className="cookie-actions">
          <button className="cookie-btn secondary" onClick={() => choose('essential')}>Essential only</button>
          <button className="cookie-btn primary" onClick={() => choose('all')}>Allow optional cookies</button>
        </div>
      </div>
    </aside>
  );
}

function LegalHeader({ title, summary }: { title: string; summary: string }) {
  return (
    <header className="legal-header">
      <div className="legal-header-content">
        <Link className="legal-back" to="/">← Back to ShambaNi</Link>
        <h1>{title}</h1>
        <p>{summary}</p>
        <span className="legal-updated">Effective {EFFECTIVE_DATE}</span>
      </div>
    </header>
  );
}

export function PrivacyPolicy() {
  return (
    <div className="legal-page">
      <LegalHeader
        title="Privacy Notice"
        summary="This notice describes the limited data handling of the current ShambaNi pre-pilot website."
      />
      <div className="legal-container">
        <section className="legal-section">
          <h2>1 Current service status</h2>
          <p>
            ShambaNi is a pre-pilot marketplace prototype based in Uganda. Public product listings, operational figures, USSD screens and transaction examples are demonstrations. Public farmer registration, buyer registration, ordering, payments, identity verification and USSD access are paused until secure production systems and required approvals are in place.
          </p>
        </section>

        <section className="legal-section">
          <h2>2 Responsible contact</h2>
          <p>
            The current project contact is ShambaNi, Mpigi, Uganda. Privacy questions can be sent to{' '}
            <a href="mailto:privacy@shambani-market.africa">privacy@shambani-market.africa</a>.
            This notice does not claim that a company, data-protection registration or regulatory authorization exists unless a current certificate is published or supplied during due diligence.
          </p>
        </section>

        <section className="legal-section">
          <h2>3 Information handled by this prototype</h2>
          <ul>
            <li>Essential browser storage used for language, cart and cookie preferences.</li>
            <li>Technical hosting logs that may be generated by the hosting provider for security and reliability.</li>
            <li>Information a visitor chooses to send through their own email application after selecting a contact link.</li>
          </ul>
          <p>
            This website does not ask visitors to submit National ID numbers or images, passwords, bank-account numbers, mobile-money PINs or payment credentials. Visitors should not send those items by email.
          </p>
        </section>

        <section className="legal-section">
          <h2>4 Purpose and retention</h2>
          <p>
            Browser preferences support basic site operation. Visitors can clear them through their browser settings. Email enquiries are used only to respond, assess pilot interest and keep an appropriate business record. Retention periods and deletion procedures will be formalized before production onboarding opens.
          </p>
        </section>

        <section className="legal-section">
          <h2>5 Future production controls</h2>
          <p>Before collecting production farmer or buyer records, ShambaNi intends to implement:</p>
          <ul>
            <li>registration with Uganda's Personal Data Protection Office where required;</li>
            <li>a documented lawful basis and consent process for each data category;</li>
            <li>server-side authentication, encryption, role-based access, audit logs, backups and incident response;</li>
            <li>contracts with hosting, telecom and payment processors;</li>
            <li>procedures for access, correction, deletion, complaints and data breaches; and</li>
            <li>a separate assessment before any National ID verification is introduced.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>6 Questions and rights</h2>
          <p>
            To ask what information ShambaNi holds about an email enquiry, request correction or deletion, or raise a privacy concern, contact{' '}
            <a href="mailto:privacy@shambani-market.africa">privacy@shambani-market.africa</a>. Regulatory questions may also be directed to Uganda's Personal Data Protection Office.
          </p>
        </section>
      </div>
    </div>
  );
}

export function TermsOfService() {
  return (
    <div className="legal-page">
      <LegalHeader
        title="Prototype Terms of Use"
        summary="These terms apply to the public ShambaNi demonstration while production services remain unavailable."
      />
      <div className="legal-container">
        <section className="legal-section">
          <h2>1 Prototype only</h2>
          <p>
            The website demonstrates a proposed farmers marketplace and operating model. It does not currently create production accounts, accept orders, process or hold payments, verify identities, provide escrow, send transaction SMS messages or operate a USSD service. No displayed short code has been allocated to ShambaNi unless confirmed separately in writing by the relevant regulator or telecom provider.
          </p>
        </section>

        <section className="legal-section">
          <h2>2 Sample content</h2>
          <p>
            Product listings, farmer profiles, reviews, prices, orders, dashboards, reports and performance figures may be sample data. They must not be treated as proof of inventory, completed sales, verified users or commercial performance.
          </p>
        </section>

        <section className="legal-section">
          <h2>3 No transaction or payment obligation</h2>
          <p>
            Adding a sample product to the cart does not reserve stock or create a contract. ShambaNi will not request a mobile-money PIN or password. Any future pilot transaction will require separate confirmation of the parties, quantity, quality, price, delivery and payment method.
          </p>
        </section>

        <section className="legal-section">
          <h2>4 Pilot enquiries</h2>
          <p>
            Farmers and buyers may email an expression of interest. An enquiry does not guarantee onboarding, verification, funding, a sale, government endorsement or admission to a pilot. Do not include confidential identity, banking, tax or payment documents in an initial enquiry.
          </p>
        </section>

        <section className="legal-section">
          <h2>5 Acceptable use</h2>
          <p>
            Visitors must not misuse the website, impersonate another person, submit unlawful content, attempt unauthorized access, or represent sample information as a completed ShambaNi transaction. The project's name and original website materials may not be used to imply an endorsement that has not been granted.
          </p>
        </section>

        <section className="legal-section">
          <h2>6 Future production terms</h2>
          <p>
            Separate marketplace terms, seller standards, buyer obligations, payment rules, complaints procedures and privacy controls will be published before production operations begin. The intended 2.5 percent buyer service fee is a proposed pilot model, not a charge currently collected through this website.
          </p>
        </section>

        <section className="legal-section">
          <h2>7 Governing law and contact</h2>
          <p>
            These prototype terms are governed by the laws of the Republic of Uganda. Questions can be sent to{' '}
            <a href="mailto:legal@shambani-market.africa">legal@shambani-market.africa</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
